# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/backend/" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "pub" # See documentation for possible values
    directory: "/appAdmin/mipedidoadmin/" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "pub" # See documentation for possible values
    directory: "/appVendedor/app_vendedor_mipedido/" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/ratingCronJob/" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/webSocketEngine/" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle" # See documentation for possible values
    directory: "/appCliente/app/" # Location of package manifests
    schedule:
      interval: "daily"
